name: Build and Test

on:
  [pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Debug

jobs:
  linux_build:
    name: "Linux Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libopencv-dev
        sudo add-apt-repository -y ppa:alex-p/tesseract-ocr5
        sudo apt install -y libtesseract-dev
        sudo rm -rf /etc/apt/trusted.gpg.d/alex-p-ubuntu-tesseract-ocr5.gpg*
        sudo rm -rf /etc/apt/sources.list.d/alex-p-ubuntu-tesseract-ocr5-jammy.list
    
    - name: Check Tesseract
      run: |
        tesseract --version

    - name: Configure CMake
      run: |
        cmake --version
        mkdir -p build
        cd build
        cmake -G "Ninja" .. -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DCMAKE_C_COMPILER="/usr/bin/cc" -DCMAKE_CXX_COMPILER="/usr/bin/c++"

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: |
        ninja
